[project]
name = "pyspark-basic"
version = "0.1.0"
description = "PySpark Basic Knowledge"
authors = [{ name = "Shawn Yu" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=40.36.0",
    "pandas==2.3.3",
    "pandas-stubs==2.3.3.260113",
    "pyarrow>=25.0.1",
    "pyspark>=4.2.0",
]

[tool.git-changelog]
bump = "auto"
convention = "conventional"
in-place = false
filter-commits = ""
marker-line = "<!-- insertion marker for GitHub -->"
output = "CHANGELOG.md"
parse-refs = true
parse-trailers = true
provider = "github"
repository = "."
sections = ["feat", "fix", "chore", "docs", "perf", "build", "refactor", "test", "deps"]
template = "angular"
version-regex = "^## \\[(?P<version>v?[^\\]]+)"
versioning = "semver"
zerover = false

[dependency-groups]
dev = [
    "black>=26.5.1",
    "git-changelog>=2.9.6",
    "ruff>=0.16.3",
]
